-- Dimension tables for the Theoria star schema.
-- Run once to bootstrap the warehouse; all tables use IF NOT EXISTS so re-runs are safe.

CREATE TABLE IF NOT EXISTS dim_movie (
    movie_id         INTEGER      NOT NULL,
    title            TEXT         NOT NULL,
    release_date     DATE,
    runtime          INTEGER,
    budget           BIGINT,
    revenue          BIGINT,
    original_language VARCHAR(10),
    status           VARCHAR(50),
    tagline          TEXT,
    poster_path      TEXT,
    backdrop_path    TEXT,
    CONSTRAINT pk_dim_movie PRIMARY KEY (movie_id)
);

CREATE TABLE IF NOT EXISTS dim_actor (
    actor_id    INTEGER      NOT NULL,
    name        TEXT         NOT NULL,
    gender      SMALLINT,
    popularity  NUMERIC(10, 4),
    profile_path TEXT,
    CONSTRAINT pk_dim_actor PRIMARY KEY (actor_id)
);

CREATE TABLE IF NOT EXISTS dim_director (
    director_id INTEGER      NOT NULL,
    name        TEXT         NOT NULL,
    gender      SMALLINT,
    popularity  NUMERIC(10, 4),
    profile_path TEXT,
    CONSTRAINT pk_dim_director PRIMARY KEY (director_id)
);

CREATE TABLE IF NOT EXISTS dim_genre (
    genre_id    INTEGER  NOT NULL,
    genre_name  TEXT     NOT NULL,
    CONSTRAINT pk_dim_genre PRIMARY KEY (genre_id)
);

-- dim_date is a pre-populated calendar table; rows are generated by the loader.
CREATE TABLE IF NOT EXISTS dim_date (
    date_id     INTEGER  NOT NULL,   -- surrogate key: YYYYMMDD integer
    full_date   DATE     NOT NULL,
    year        SMALLINT NOT NULL,
    month       SMALLINT NOT NULL,
    day         SMALLINT NOT NULL,
    decade      SMALLINT NOT NULL,   -- e.g. 1990, 2000, 2010
    CONSTRAINT pk_dim_date PRIMARY KEY (date_id)
);
