-- Dimension tables for the Theoria star schema — the current schema.
-- Run once to bootstrap the warehouse; all tables use IF NOT EXISTS so re-runs are safe.
--
-- Files 04-11 are historical migrations that brought an already-live warehouse
-- to this shape. A fresh database needs only 01-03; running the migrations on
-- top is harmless but unnecessary, and 11 would drop tables 01 no longer creates.

-- Declared before dim_movie because dim_movie carries an FK to it. Roughly half
-- the catalog belongs to no collection, so that FK is nullable by design.
CREATE TABLE IF NOT EXISTS dim_collection (
    collection_id INTEGER      NOT NULL,
    name          TEXT         NOT NULL,
    poster_path   TEXT,
    slug          VARCHAR(300),
    CONSTRAINT pk_dim_collection PRIMARY KEY (collection_id)
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_dim_collection_slug ON dim_collection (slug);

CREATE TABLE IF NOT EXISTS dim_movie (
    movie_id         INTEGER      NOT NULL,
    title            TEXT         NOT NULL,
    release_date     DATE,
    runtime          INTEGER,
    budget           BIGINT,
    revenue          BIGINT,
    original_language VARCHAR(10),
    status           VARCHAR(50),
    overview         TEXT,
    tagline          TEXT,
    poster_path      TEXT,
    backdrop_path    TEXT,
    slug             VARCHAR(300),
    collection_id    INTEGER,
    CONSTRAINT pk_dim_movie PRIMARY KEY (movie_id),
    CONSTRAINT fk_dim_movie_collection FOREIGN KEY (collection_id) REFERENCES dim_collection (collection_id)
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_dim_movie_slug ON dim_movie (slug);
CREATE INDEX IF NOT EXISTS idx_dim_movie_collection_id ON dim_movie (collection_id);

-- Every person holding any credit, in any department. What they did on a given
-- film lives in fact_credit, not in which table they land in. See
-- 08_person_credits.sql for why this replaced the dim_actor/dim_director split.
CREATE TABLE IF NOT EXISTS dim_person (
    person_id            INTEGER      NOT NULL,
    name                 TEXT         NOT NULL,
    gender               SMALLINT,
    popularity           NUMERIC(10, 4),
    profile_path         TEXT,
    known_for_department TEXT,
    slug                 VARCHAR(300),
    CONSTRAINT pk_dim_person PRIMARY KEY (person_id)
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_dim_person_slug ON dim_person (slug);

CREATE TABLE IF NOT EXISTS dim_genre (
    genre_id    INTEGER  NOT NULL,
    genre_name  TEXT     NOT NULL,
    CONSTRAINT pk_dim_genre PRIMARY KEY (genre_id)
);

-- dim_date is a pre-populated calendar table; rows are generated by the loader.
CREATE TABLE IF NOT EXISTS dim_date (
    date_id     INTEGER  NOT NULL,   -- surrogate key: YYYYMMDD integer
    full_date   DATE     NOT NULL,
    year        SMALLINT NOT NULL,
    month       SMALLINT NOT NULL,
    day         SMALLINT NOT NULL,
    decade      SMALLINT NOT NULL,   -- e.g. 1990, 2000, 2010
    CONSTRAINT pk_dim_date PRIMARY KEY (date_id)
);
