-- Dimension tables for the Theoria star schema.
-- Run once to bootstrap the warehouse; all tables use IF NOT EXISTS so re-runs are safe.

CREATE TABLE IF NOT EXISTS dim_movie (
    movie_id         INTEGER      NOT NULL,
    title            TEXT         NOT NULL,
    release_date     DATE,
    runtime          INTEGER,
    budget           BIGINT,
    revenue          BIGINT,
    original_language VARCHAR(10),
    status           VARCHAR(50),
    overview         TEXT,
    tagline          TEXT,
    poster_path      TEXT,
    backdrop_path    TEXT,
    slug             VARCHAR(300),
    CONSTRAINT pk_dim_movie PRIMARY KEY (movie_id)
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_dim_movie_slug ON dim_movie (slug);

-- Every person holding any credit, in any department. What they did on a given
-- film lives in fact_credit, not in which table they land in. See
-- 08_person_credits.sql for why this replaced the dim_actor/dim_director split.
CREATE TABLE IF NOT EXISTS dim_person (
    person_id            INTEGER      NOT NULL,
    name                 TEXT         NOT NULL,
    gender               SMALLINT,
    popularity           NUMERIC(10, 4),
    profile_path         TEXT,
    known_for_department TEXT,
    slug                 VARCHAR(300),
    CONSTRAINT pk_dim_person PRIMARY KEY (person_id)
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_dim_person_slug ON dim_person (slug);

CREATE TABLE IF NOT EXISTS dim_actor (
    actor_id    INTEGER      NOT NULL,
    name        TEXT         NOT NULL,
    gender      SMALLINT,
    popularity  NUMERIC(10, 4),
    profile_path TEXT,
    slug        VARCHAR(300),
    CONSTRAINT pk_dim_actor PRIMARY KEY (actor_id)
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_dim_actor_slug ON dim_actor (slug);

CREATE TABLE IF NOT EXISTS dim_director (
    director_id INTEGER      NOT NULL,
    name        TEXT         NOT NULL,
    gender      SMALLINT,
    popularity  NUMERIC(10, 4),
    profile_path TEXT,
    slug        VARCHAR(300),
    CONSTRAINT pk_dim_director PRIMARY KEY (director_id)
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_dim_director_slug ON dim_director (slug);

CREATE TABLE IF NOT EXISTS dim_genre (
    genre_id    INTEGER  NOT NULL,
    genre_name  TEXT     NOT NULL,
    CONSTRAINT pk_dim_genre PRIMARY KEY (genre_id)
);

-- dim_date is a pre-populated calendar table; rows are generated by the loader.
CREATE TABLE IF NOT EXISTS dim_date (
    date_id     INTEGER  NOT NULL,   -- surrogate key: YYYYMMDD integer
    full_date   DATE     NOT NULL,
    year        SMALLINT NOT NULL,
    month       SMALLINT NOT NULL,
    day         SMALLINT NOT NULL,
    decade      SMALLINT NOT NULL,   -- e.g. 1990, 2000, 2010
    CONSTRAINT pk_dim_date PRIMARY KEY (date_id)
);
