# Generated by Django 5.1.4 on 2026-09-12 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('purpose', models.CharField(choices=[('signup', 'Sign up'), ('login', 'Log in')], max_length=10)),
                ('code_hash', models.CharField(max_length=64)),
                ('pending_username', models.CharField(blank=True, max_length=30, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'indexes': [models.Index(fields=['email', 'purpose', '-created_at'], name='idx_logincode_lookup')],
                'constraints': [models.CheckConstraint(condition=models.Q(('purpose__in', ['signup', 'login'])), name='ck_logincode_purpose')],
            },
        ),
    ]
